apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: web
          image: php:8.2-fpm
          ports:
            - containerPort: 8080
            - containerPort: 22
          volumeMounts:
            - mountPath: /var/www/html
              name: laravel-code
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && apt-get install -y \
                nginx git unzip openssh-server libzip-dev libxml2-dev libcurl4-openssl-dev pkg-config libssl-dev libonig-dev && \
              docker-php-ext-install pdo_mysql mbstring xml zip bcmath curl && \
              service nginx start && \
              git clone https://github.com/SSINAT/Final-Devops.git /var/www/html && \
              tail -f /dev/null
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_DATABASE
              value: "terrain_booking"
            - name: MYSQL_ROOT_PASSWORD
              value: "Hello@123"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql

      volumes:
        - name: laravel-code
          emptyDir: {}
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
